### ISSUE TITLE
general :: footer

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-playastijuana#24]
Ahorita al hacer scroll y llegar a la parte de abajo en automático se muestran más lugares, lo que genera que el footer no sea alcanzable ... de momento puse un límite de 3 requests, para que puedas probar y ver el footer.

Esto es parte de lo que habias comentado sobre implementar un footer fixed tipo btn que abra el footer cuando el usuario lo solicite, lo que me preocupa es perder SEO, pues ahorita ya estamos dentro de las primeras 3 posiciones, pero podemos experimentar y en caso de afectar regresar al estado actual.

La justificación de lazyloading (mostrar mas ofertas al llegar al footer), es ayudar a que la página se cargue más rápido, pues ahorita en www mostramos casi 100 lugares al cargar la página, si es la primera vez que la cargas (sin cache) tarda unos segundos, ya las siguientes cargas son más rápidas.

qué opinas? sugerencias?

<img width="1230" alt="screen shot 2016-05-17 at 11 24 48 am" src="https://cloud.githubusercontent.com/assets/7799215/15330483/a5b023b0-1c22-11e6-97b5-4e55349d100b.png">

**Comment by ale-romo** [comment]
Opino dos cosas: 
a) por como están configurados los cards pueden caber más de uno por renglón, haciendo que 100 lugares solo ocupen 30 renglones.
b) podemos dejar el footer como está, que en teoría esta visible, y que cuando se presione el botón de footer se le agregue una clase fixed, y que se pueda quitar también, de esa manera no perdemos SEO tampoco.

Opino activar ambas opciones.

**Comment by garciadiazjaime** [comment]
omitiria a) en espera de la sugerencia que mandara pool, a menos que crees conveniente nos vayamos a 2 cards por renglone

referente a b) dices dejar el footer como esta y agregar este btn 'footer' que pondra clase fixed? si te refieres a esto me parece buena idea

**Comment by ale-romo** [comment]
Arre quedó b) no está bulletproof pero quedó bien.

**Comment by garciadiazjaime** [comment]
se ve bien, lo único es que en web le puedes seguir dando scroll al contenido del fondo.. en el PS puedes ver la barra, hay forma de mejorarlo? pues está medio raro eso de poder hacer scroll

<img width="1440" alt="screen shot 2016-05-28 at 12 46 14 pm" src="https://cloud.githubusercontent.com/assets/7799215/15628872/730d8ea8-24d2-11e6-8932-c95ca9a185fe.png">

**Comment by ale-romo** [comment]
Fixed
