### ISSUE TITLE
general :: social media

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-playastijuana#25]
Creé dos cuentas: fb, g+

De momento puse los links en el footer sin estilo, estaría cool darles estilo y quizás ponerlas también en el header, cómo ves?

<img width="1081" alt="screen shot 2016-05-17 at 11 31 26 am" src="https://cloud.githubusercontent.com/assets/7799215/15330559/0b379362-1c23-11e6-9d88-f86dc7b8b171.png">

En un punto esas cuentas serán alimentadas de manera automática, de momento no tienen contenido pero su existencia ayuda con seo.

**Comment by ale-romo** [comment]
arre, I'm on it

**Comment by ale-romo** [comment]
Ya quedó en el footer, había un glitch raro pero ya está.

**Comment by ale-romo** [comment]
Y ya quedó el header
