### ISSUE TITLE
rd :: banner imgs

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-playastijuana#27]
se puede mejorar como se ven las imgs? centrarlas quizas?
por ej, slide 2 y 3 (mint principalmente) se pierde bastante el enfoque

slide 2
<img width="432" alt="screen shot 2016-05-17 at 11 56 14 am" src="https://cloud.githubusercontent.com/assets/7799215/15331513/4192d6ca-1c27-11e6-837e-15152d0e45c6.png">

slide 3
<img width="427" alt="screen shot 2016-05-17 at 11 56 24 am" src="https://cloud.githubusercontent.com/assets/7799215/15331516/45b00ab6-1c27-11e6-9b8e-5236eae6383e.png">

**Comment by ale-romo** [comment]
Ya está centrado, pero todavía se ve medio piraton.
