### ISSUE TITLE
rd :: card

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-playastijuana#28]
podemos mejorar la posición de los elementos?
- título y súbtitlo estaría cool tenerlos en misma altura que la img
- hacer un poco más grande la img
- hacer ligeramente más pequeños los íconos sm y en la misma línea

<img width="443" alt="screen shot 2016-05-17 at 11 56 35 am" src="https://cloud.githubusercontent.com/assets/7799215/15331592/a247e640-1c27-11e6-8761-251a73394f67.png">

**Comment by ale-romo** [comment]
done

**Comment by garciadiazjaime** [comment]
puedes subir titulo y categoria a la derecha de la img? lo mismo para movil, y hacer mas grande la img

<img width="398" alt="screen shot 2016-06-03 at 9 07 33 am" src="https://cloud.githubusercontent.com/assets/7799215/15781213/acb1aec2-296a-11e6-84d1-95638be5d1e5.png">

**Comment by ale-romo** [comment]
done
