### ISSUE TITLE
general :: svg google maps

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-playastijuana#31]
puedes pasar el icono a fondo solido verde y la G?
Esto para tener los logos homologados en cuanto a todos solidos de fondo y solo con Letra o icono para el caso de twitter .... por otra parte en el boilerplate los tenemos bajo un color digamos gris y en hover se ponen de su color (azul para FB/twitter, verde para G) entonces me parece lo mejor es todos tenerlos con fondo solido .. que opinas?
<img width="83" alt="screen shot 2016-06-01 at 10 46 40 am" src="https://cloud.githubusercontent.com/assets/7799215/15716180/e5822298-27e6-11e6-9fa6-de198e41f8dc.png">

**Comment by ale-romo** [comment]
Opino que el de google maps (que no es red social), queda más claro si lo mantenemos como está. 
Igual si voy a crear uno para google+
